<?php

/**
 * PartumArtificiumForumThread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    partum-artificium-server
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartumArtificiumForumThread extends BasePartumArtificiumForumThread
{
  public function getLatestEntry()
  {
    $latest_entry = null;
    foreach ($this->getEntries() as $entry) {
      if (is_null($latest_entry)) $latest_entry = $entry;
      $latest_entry = $latest_entry->getCreatedAt() < $entry->getCreatedAt() ? $latest_entry : $entry;
    }
    return $latest_entry;
  }

  public function getEntryCount()
  {
    return count($this->getEntries());
  }
}
