<?php

/**
 * PartumArtificiumForum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    partum-artificium-server
 * @subpackage model
 * @author     Alex Brandt <alunduil@alunduil.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartumArtificiumForum extends BasePartumArtificiumForum
{
  public function getThreadCount()
  {
    return count($this->getPartumArtificiumForumThread());
  }

  public function getPostCount()
  {
    $count = 0;
    foreach ($this->getPartumArtificiumForumThread() as $thread) {
      $count += count($thread->getPartumArtificiumForumEntry());
    }
    return $count;
  }

  public function getMostRecentPost()
  {
  }
}
