<?php

/**
 * PartumArtificiumForumThread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    partum-artificium-server
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartumArtificiumForumThread extends BasePartumArtificiumForumThread
{
  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew()) {
      $forum = $this->getForum();
      $forum->incrementThreadCount();
      $forum->save();
    }

    return parent::save($conn);
  }

  public function incrementEntryCount($increment = 1)
  {
    $this->setEntryCount($this->getEntryCount() + $increment);
  }
}
