<?php

/**
 * PartumArtificiumForumEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    partum-artificium-server
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartumArtificiumForumEntry extends BasePartumArtificiumForumEntry
{
  public function save(Doctrine_Connection $conn = null)
  {

    if ($this->isNew()) {
      $ret = parent::save($conn);
      
      $thread = $this->getThread();
      $thread->incrementEntryCount();
      $thread->setLatestEntryId($this->getId());
      $thread->save($conn);

      $forum = $this->getThread()->getForum();
      $forum->incrementEntryCount();
      $forum->setLatestEntryId($this->getId());
      $forum->save($conn);
    } else {
      $ret = parent::save($conn);
    }

    return $ret;
  }
}
