<?php

/**
 * PartumArtificiumForum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    partum-artificium-server
 * @subpackage model
 * @author     Alex Brandt <alunduil@alunduil.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartumArtificiumForum extends BasePartumArtificiumForum
{
  public function incrementThreadCount($increment = 1)
  {
    $this->setThreadCount($this->getThreadCount() + $increment);
  }

  public function incrementEntryCount($increment = 1)
  {
    $this->setEntryCount($this->getEntryCount() + $increment);
  }

  public function getLatestEntry()
  {
    if (!is_null($this->getLatestEntryId()) && is_null($this->latest_entry)) {
      $this->latest_entry = Doctrine::getTable('PartumArtificiumForumEntry')->find($this->getLatestEntryId());
    }
    return $this->latest_entry;
  }

  private $latest_entry = null;
}
