<?php

/**
 * PartumArtificiumPlayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    partum-artificium-server
 * @subpackage model
 * @author     Alex Brandt <alunduil@alunduil.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartumArtificiumPlayer extends BasePartumArtificiumPlayer
{
  public function __toString()
  {
    return $this->getUserName();
  }
}
