# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

forums:
  url: /forums
  param: { module: forum, action: index }

threads:
  url: /forums/:forum_slug
  param: { module: forum, action: show }

thread:
  url: /forums/:forum_slug/:thread_slug
  param: { module: thread, action: show }

entry:
  url: /forums/:forum_slug/:thread_slug/#:entry_slug
  param: { module: thread, action: show }

player:
  url: /players/:user_name
  param: { module: player, action: show }

