### Tag Models ###

PartumArtificiumTag:
  actAs:
    Sluggable: { fields: [name] }
  columns:
    name: { type: string(255), notnull: true, unique: true }

### Forum Models ###

PartumArtificiumForum:
  actAs:
    Timestampable: ~
    Sluggable: { fields: [title] }
  columns:
    title: { type: string(255), notnull: true, unique: true }
    moderator_id: { type: integer }
  relations:
    moderator: { class: PartumArtificiumPlayer, onUpdate: CASCADE, onDelete: SET NULL, local: moderator_id, foreign: id }

PartumArtificiumForumThread:
  actAs: 
    Timestampable: ~
    Sluggable: { fields: [subject] }
  columns:
    subject: { type: string(255) }
    forum_id: { type: integer }
  relations:
    forum: { class: PartumArtificiumForum, onUpdate: CASCADE, onDelete: CASCADE, local: forum_id, foreign: id }

PartumArtificiumForumEntry:
  actAs:
    Timestampable: ~
    Sluggable: { fields: [subject] }
  columns:
    subject: { type: string(255) }
    body: { type: string(4096), notnull: true }
    thread_id: { type: integer }
    tags_id: { type: integer }
    author_id: { type: integer }
  relations:
    thread: { class: PartumArtificiumForumThread, onUpdate: CASCADE, onDelete: CASCADE, local: thread_id, foreign: id }
    tags:
      class: PartumArtificiumTag
      refClass: PartumArtificiumEntryTag
      local: entry_id
      foreign: tag_id
      foreignAlias: PartumArtificiumTags
    author: { class: PartumArtificiumPlayer, onUpdate: CASCADE, onDelete: SET NULL, local: author_id, foreign: id }

PartumArtificiumEntryTag:
  columns:
    entry_id: { type: integer, primary: true }
    tag_id: { type: integer, primary: true }
  relations:
    entry: { class: PartumArtificiumForumEntry, onUpdate: CASCADE, onDelete: CASCADE, local: entry_id, foreign: id }
    tag: { class: PartumArtificiumTag, onUpdate: CASCADE, onDelete: CASCADE, local: tag_id, foreign: id }
    
### Player Models ###

PartumArtificiumPlayer:
  actAs:
    Timestampable: ~
    Sluggable: { fields: [user_name] }
  columns:
    user_name: { type: string(255), notnull: true, unique: true }
    picture_path: { type: string(255), unique: true }
